[package]
name = "twammbridge"
version = "0.1.0"

[dependencies]
ekubo = { git = "https://github.com/ekuboprotocol/abis" }
starknet = ">=2.3.0"


[[tool.snforge.fork]]
name = "mainnet"
url = "https://free-rpc.nethermind.io/mainnet-juno"
block_id.number = "677957"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.30.0" }
assert_macros = "2.8.2"

[[target.starknet-contract]]

