[package]
name = "twammbridge"
version = "0.1.0"
edition = "2023_11"

[dependencies]
ekubo = { git = "https://github.com/ekuboprotocol/abis" }
starknet = ">=2.6.2"


[[tool.snforge.fork]]
name = "mainnet"
url = "https://free-rpc.nethermind.io/mainnet-juno"
block_id.number = "677957"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.24.0" }
assert_macros = "2.8.2"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

